### ISSUE TITLE
Add password support

### ISSUE THREAD

**Issue by therealromster** [prologic/kdb#36]
Feature request for using /pass to authenticate with oauth

http://help.twitch.tv/customer/portal/articles/1302780-twitch-irc#Hexchat%20Guide

https://twitchapps.com/tmi/

**Comment by prologic** [comment]
Add password support for connecting to password protected IRC servers by adding support for sending the `PASS <password>` IRC Command. This needs to be configurable as well via configuration file `kdb.ini`, command line option or environment.
