### ISSUE TITLE
Allow kdb to connect over SSL connections and ports.

### ISSUE THREAD

**Issue by therealromster** [prologic/kdb#4]
Allow SSL sockets for a secure connection to the ircd.
##

**Comment by prologic** [comment]
:+1: -- Q: Can we _assume_ certain ports here or do we need a `tcps://` URI schema or `-s/--ssl` option? (_I prefer the later I guess as it can be put into configuration files and specified via env vars too_).

**Comment by therealromster** [comment]
What IRC clients do is append a + to the port number, we can do the same to denote use SSL transport. +6697 +7000 and +7070 for freenode.

All freenode servers listen on ports 6665, 6666, 6667, 6697 (SSL only), 7000 (SSL only), 7070 (SSL only), 8000, 8001 and 8002.

**Comment by prologic** [comment]
Gotcha; sounds good to me. I think this is ready to implement!

**Comment by prologic** [comment]
Waiting on circuits/circuits#114
