### ISSUE TITLE
ACL list for modules

### ISSUE THREAD

**Issue by therealromster** [prologic/kdb#5]
I would like to use an ACL list for allowing and restricting what commands in each plugin a user can issue.

This could be done by flags or even subscribe a user to a channel. Users would need to identify to the bot. However some commands could use nickserv to see if the nick is identified to a specific user account name, and channel access list possibly.
##

**Comment by prologic** [comment]
Seems to be two features here :) Which are we implementing? Are we going to implement this in _one_ plugin or split/separate it out into _two_?

I can see this working as a new plugin that "intercepts" commands and filters them based on whether the user has permission to "execute" that command.

Question is; how do we want this "permission" list specified?

**Comment by therealromster** [comment]
This should be two plugins, one that uses the channel list and any chanop users, the other plugin using a flatfile database or json... or something database that the bot can read and write, add and remove entries.

**Comment by prologic** [comment]
Hmm let's spend a bit more time on this one; it's not yet exactly clear to me how this _should_ work :)

**Comment by prologic** [comment]
Some useful tools and libraires:
- [simpleacl](https://github.com/kyleterry/simpleacl-py)
- [miracle-acl](https://github.com/kolypto/py-miracle)

**Comment by prologic** [comment]
Thinking about the following configuration:

``` #!ini
[acl.groups]
owner = '^.*$'
admin = ['^(load|unload).*$']
users = ['^uptime$', '^[cnm]stats$']

[acl.users]
prologic = ['admin']
romster = ['admin', 'users']
* = ['users']
```
