### ISSUE TITLE
Allow to configure ident and name fields

### ISSUE THREAD

**Issue by therealromster** [prologic/kdb#6]
Allow to set a custom indent and name filed, so it can be customized to the users purpose.

**Comment by prologic** [comment]
What's the use-case behind this? (_just curious_). The `ident` or "identity" is kind of unique to the software I think; I could see how customizing the `name` however could be useful so others on a Server/Network could `/whois` the bot and see what it's for, etc. -- Could parts of the `kdb` name still remain? Perhaps allow "some" customization of the `name` (_templated_)?

**Comment by therealromster** [comment]
I guess ident could remain. the name field how ever could be useful for extra information about the bot owner or it's purpose.

**Comment by prologic** [comment]
let's make the `name` field configurable then with some extra info?
