### ISSUE TITLE
starting KDB I get this error.

### ISSUE THREAD

**Issue by therealromster** [prologic/kdb#8]
$ docker logs $CID
Loading plugins...
Registered Component: <Channels/bot 1:MainThread (queued=0) [S]>
Loaded plugin: Channels
Registered Component: <Core/bot 1:MainThread (queued=0) [S]>
Loaded plugin: Core
Registered Component: <IRC/bot 1:MainThread (queued=0) [S]>
Loaded plugin: IRC
Registered Component: <Help/bot 1:MainThread (queued=0) [S]>
Loaded plugin: Help
Registered Component: <AutoID/bot 1:MainThread (queued=0) [S]>
Loaded plugin: AutoID
Unknown Command: this
Unknown Command: [#circuits]

**Comment by prologic** [comment]
Fixed the first one in 03b26224ed8ca259d63083cdcf09274278f0b8ef

**Comment by prologic** [comment]
Superseded by #9
